# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/antoine/Workspace/c/Shell

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/antoine/Workspace/c/Shell

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/antoine/Workspace/c/Shell/CMakeFiles /home/antoine/Workspace/c/Shell/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/antoine/Workspace/c/Shell/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named clear_lib

# Build rule for target.
clear_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clear_lib
.PHONY : clear_lib

# fast build rule for target.
clear_lib/fast:
	$(MAKE) -f CMakeFiles/clear_lib.dir/build.make CMakeFiles/clear_lib.dir/build
.PHONY : clear_lib/fast

#=============================================================================
# Target rules for targets named ps_lib

# Build rule for target.
ps_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ps_lib
.PHONY : ps_lib

# fast build rule for target.
ps_lib/fast:
	$(MAKE) -f CMakeFiles/ps_lib.dir/build.make CMakeFiles/ps_lib.dir/build
.PHONY : ps_lib/fast

#=============================================================================
# Target rules for targets named ps

# Build rule for target.
ps: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ps
.PHONY : ps

# fast build rule for target.
ps/fast:
	$(MAKE) -f CMakeFiles/ps.dir/build.make CMakeFiles/ps.dir/build
.PHONY : ps/fast

#=============================================================================
# Target rules for targets named more

# Build rule for target.
more: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 more
.PHONY : more

# fast build rule for target.
more/fast:
	$(MAKE) -f CMakeFiles/more.dir/build.make CMakeFiles/more.dir/build
.PHONY : more/fast

#=============================================================================
# Target rules for targets named chgrp

# Build rule for target.
chgrp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chgrp
.PHONY : chgrp

# fast build rule for target.
chgrp/fast:
	$(MAKE) -f CMakeFiles/chgrp.dir/build.make CMakeFiles/chgrp.dir/build
.PHONY : chgrp/fast

#=============================================================================
# Target rules for targets named clear

# Build rule for target.
clear: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clear
.PHONY : clear

# fast build rule for target.
clear/fast:
	$(MAKE) -f CMakeFiles/clear.dir/build.make CMakeFiles/clear.dir/build
.PHONY : clear/fast

#=============================================================================
# Target rules for targets named top_lib

# Build rule for target.
top_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 top_lib
.PHONY : top_lib

# fast build rule for target.
top_lib/fast:
	$(MAKE) -f CMakeFiles/top_lib.dir/build.make CMakeFiles/top_lib.dir/build
.PHONY : top_lib/fast

#=============================================================================
# Target rules for targets named more_lib

# Build rule for target.
more_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 more_lib
.PHONY : more_lib

# fast build rule for target.
more_lib/fast:
	$(MAKE) -f CMakeFiles/more_lib.dir/build.make CMakeFiles/more_lib.dir/build
.PHONY : more_lib/fast

#=============================================================================
# Target rules for targets named chown_lib

# Build rule for target.
chown_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chown_lib
.PHONY : chown_lib

# fast build rule for target.
chown_lib/fast:
	$(MAKE) -f CMakeFiles/chown_lib.dir/build.make CMakeFiles/chown_lib.dir/build
.PHONY : chown_lib/fast

#=============================================================================
# Target rules for targets named chown

# Build rule for target.
chown: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chown
.PHONY : chown

# fast build rule for target.
chown/fast:
	$(MAKE) -f CMakeFiles/chown.dir/build.make CMakeFiles/chown.dir/build
.PHONY : chown/fast

#=============================================================================
# Target rules for targets named top

# Build rule for target.
top: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 top
.PHONY : top

# fast build rule for target.
top/fast:
	$(MAKE) -f CMakeFiles/top.dir/build.make CMakeFiles/top.dir/build
.PHONY : top/fast

#=============================================================================
# Target rules for targets named chmod_lib

# Build rule for target.
chmod_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chmod_lib
.PHONY : chmod_lib

# fast build rule for target.
chmod_lib/fast:
	$(MAKE) -f CMakeFiles/chmod_lib.dir/build.make CMakeFiles/chmod_lib.dir/build
.PHONY : chmod_lib/fast

#=============================================================================
# Target rules for targets named chmod

# Build rule for target.
chmod: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chmod
.PHONY : chmod

# fast build rule for target.
chmod/fast:
	$(MAKE) -f CMakeFiles/chmod.dir/build.make CMakeFiles/chmod.dir/build
.PHONY : chmod/fast

#=============================================================================
# Target rules for targets named mv_lib

# Build rule for target.
mv_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mv_lib
.PHONY : mv_lib

# fast build rule for target.
mv_lib/fast:
	$(MAKE) -f CMakeFiles/mv_lib.dir/build.make CMakeFiles/mv_lib.dir/build
.PHONY : mv_lib/fast

#=============================================================================
# Target rules for targets named echo_lib

# Build rule for target.
echo_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 echo_lib
.PHONY : echo_lib

# fast build rule for target.
echo_lib/fast:
	$(MAKE) -f CMakeFiles/echo_lib.dir/build.make CMakeFiles/echo_lib.dir/build
.PHONY : echo_lib/fast

#=============================================================================
# Target rules for targets named cp

# Build rule for target.
cp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cp
.PHONY : cp

# fast build rule for target.
cp/fast:
	$(MAKE) -f CMakeFiles/cp.dir/build.make CMakeFiles/cp.dir/build
.PHONY : cp/fast

#=============================================================================
# Target rules for targets named echo

# Build rule for target.
echo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 echo
.PHONY : echo

# fast build rule for target.
echo/fast:
	$(MAKE) -f CMakeFiles/echo.dir/build.make CMakeFiles/echo.dir/build
.PHONY : echo/fast

#=============================================================================
# Target rules for targets named shell

# Build rule for target.
shell: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shell
.PHONY : shell

# fast build rule for target.
shell/fast:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/build
.PHONY : shell/fast

#=============================================================================
# Target rules for targets named du_lib

# Build rule for target.
du_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 du_lib
.PHONY : du_lib

# fast build rule for target.
du_lib/fast:
	$(MAKE) -f CMakeFiles/du_lib.dir/build.make CMakeFiles/du_lib.dir/build
.PHONY : du_lib/fast

#=============================================================================
# Target rules for targets named cat_lib

# Build rule for target.
cat_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cat_lib
.PHONY : cat_lib

# fast build rule for target.
cat_lib/fast:
	$(MAKE) -f CMakeFiles/cat_lib.dir/build.make CMakeFiles/cat_lib.dir/build
.PHONY : cat_lib/fast

#=============================================================================
# Target rules for targets named ls

# Build rule for target.
ls: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ls
.PHONY : ls

# fast build rule for target.
ls/fast:
	$(MAKE) -f CMakeFiles/ls.dir/build.make CMakeFiles/ls.dir/build
.PHONY : ls/fast

#=============================================================================
# Target rules for targets named ls_lib

# Build rule for target.
ls_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ls_lib
.PHONY : ls_lib

# fast build rule for target.
ls_lib/fast:
	$(MAKE) -f CMakeFiles/ls_lib.dir/build.make CMakeFiles/ls_lib.dir/build
.PHONY : ls_lib/fast

#=============================================================================
# Target rules for targets named pwd

# Build rule for target.
pwd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pwd
.PHONY : pwd

# fast build rule for target.
pwd/fast:
	$(MAKE) -f CMakeFiles/pwd.dir/build.make CMakeFiles/pwd.dir/build
.PHONY : pwd/fast

#=============================================================================
# Target rules for targets named cd

# Build rule for target.
cd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cd
.PHONY : cd

# fast build rule for target.
cd/fast:
	$(MAKE) -f CMakeFiles/cd.dir/build.make CMakeFiles/cd.dir/build
.PHONY : cd/fast

#=============================================================================
# Target rules for targets named chgrp_lib

# Build rule for target.
chgrp_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chgrp_lib
.PHONY : chgrp_lib

# fast build rule for target.
chgrp_lib/fast:
	$(MAKE) -f CMakeFiles/chgrp_lib.dir/build.make CMakeFiles/chgrp_lib.dir/build
.PHONY : chgrp_lib/fast

#=============================================================================
# Target rules for targets named cat

# Build rule for target.
cat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cat
.PHONY : cat

# fast build rule for target.
cat/fast:
	$(MAKE) -f CMakeFiles/cat.dir/build.make CMakeFiles/cat.dir/build
.PHONY : cat/fast

#=============================================================================
# Target rules for targets named pwd_lib

# Build rule for target.
pwd_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pwd_lib
.PHONY : pwd_lib

# fast build rule for target.
pwd_lib/fast:
	$(MAKE) -f CMakeFiles/pwd_lib.dir/build.make CMakeFiles/pwd_lib.dir/build
.PHONY : pwd_lib/fast

#=============================================================================
# Target rules for targets named rm

# Build rule for target.
rm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rm
.PHONY : rm

# fast build rule for target.
rm/fast:
	$(MAKE) -f CMakeFiles/rm.dir/build.make CMakeFiles/rm.dir/build
.PHONY : rm/fast

#=============================================================================
# Target rules for targets named mv

# Build rule for target.
mv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mv
.PHONY : mv

# fast build rule for target.
mv/fast:
	$(MAKE) -f CMakeFiles/mv.dir/build.make CMakeFiles/mv.dir/build
.PHONY : mv/fast

#=============================================================================
# Target rules for targets named mkdir

# Build rule for target.
mkdir: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mkdir
.PHONY : mkdir

# fast build rule for target.
mkdir/fast:
	$(MAKE) -f CMakeFiles/mkdir.dir/build.make CMakeFiles/mkdir.dir/build
.PHONY : mkdir/fast

#=============================================================================
# Target rules for targets named mkdir_lib

# Build rule for target.
mkdir_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mkdir_lib
.PHONY : mkdir_lib

# fast build rule for target.
mkdir_lib/fast:
	$(MAKE) -f CMakeFiles/mkdir_lib.dir/build.make CMakeFiles/mkdir_lib.dir/build
.PHONY : mkdir_lib/fast

#=============================================================================
# Target rules for targets named rm_lib

# Build rule for target.
rm_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rm_lib
.PHONY : rm_lib

# fast build rule for target.
rm_lib/fast:
	$(MAKE) -f CMakeFiles/rm_lib.dir/build.make CMakeFiles/rm_lib.dir/build
.PHONY : rm_lib/fast

#=============================================================================
# Target rules for targets named du

# Build rule for target.
du: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 du
.PHONY : du

# fast build rule for target.
du/fast:
	$(MAKE) -f CMakeFiles/du.dir/build.make CMakeFiles/du.dir/build
.PHONY : du/fast

#=============================================================================
# Target rules for targets named connect

# Build rule for target.
connect: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 connect
.PHONY : connect

# fast build rule for target.
connect/fast:
	$(MAKE) -f CMakeFiles/connect.dir/build.make CMakeFiles/connect.dir/build
.PHONY : connect/fast

#=============================================================================
# Target rules for targets named connect_lib

# Build rule for target.
connect_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 connect_lib
.PHONY : connect_lib

# fast build rule for target.
connect_lib/fast:
	$(MAKE) -f CMakeFiles/connect_lib.dir/build.make CMakeFiles/connect_lib.dir/build
.PHONY : connect_lib/fast

#=============================================================================
# Target rules for targets named cp_lib

# Build rule for target.
cp_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cp_lib
.PHONY : cp_lib

# fast build rule for target.
cp_lib/fast:
	$(MAKE) -f CMakeFiles/cp_lib.dir/build.make CMakeFiles/cp_lib.dir/build
.PHONY : cp_lib/fast

src/commands.o: src/commands.c.o

.PHONY : src/commands.o

# target to build an object file
src/commands.c.o:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands.c.o
.PHONY : src/commands.c.o

src/commands.i: src/commands.c.i

.PHONY : src/commands.i

# target to preprocess a source file
src/commands.c.i:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands.c.i
.PHONY : src/commands.c.i

src/commands.s: src/commands.c.s

.PHONY : src/commands.s

# target to generate assembly for a file
src/commands.c.s:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands.c.s
.PHONY : src/commands.c.s

src/commands/cat.o: src/commands/cat.c.o

.PHONY : src/commands/cat.o

# target to build an object file
src/commands/cat.c.o:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/cat.c.o
	$(MAKE) -f CMakeFiles/cat_lib.dir/build.make CMakeFiles/cat_lib.dir/src/commands/cat.c.o
	$(MAKE) -f CMakeFiles/cat.dir/build.make CMakeFiles/cat.dir/src/commands/cat.c.o
.PHONY : src/commands/cat.c.o

src/commands/cat.i: src/commands/cat.c.i

.PHONY : src/commands/cat.i

# target to preprocess a source file
src/commands/cat.c.i:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/cat.c.i
	$(MAKE) -f CMakeFiles/cat_lib.dir/build.make CMakeFiles/cat_lib.dir/src/commands/cat.c.i
	$(MAKE) -f CMakeFiles/cat.dir/build.make CMakeFiles/cat.dir/src/commands/cat.c.i
.PHONY : src/commands/cat.c.i

src/commands/cat.s: src/commands/cat.c.s

.PHONY : src/commands/cat.s

# target to generate assembly for a file
src/commands/cat.c.s:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/cat.c.s
	$(MAKE) -f CMakeFiles/cat_lib.dir/build.make CMakeFiles/cat_lib.dir/src/commands/cat.c.s
	$(MAKE) -f CMakeFiles/cat.dir/build.make CMakeFiles/cat.dir/src/commands/cat.c.s
.PHONY : src/commands/cat.c.s

src/commands/cd.o: src/commands/cd.c.o

.PHONY : src/commands/cd.o

# target to build an object file
src/commands/cd.c.o:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/cd.c.o
	$(MAKE) -f CMakeFiles/cd.dir/build.make CMakeFiles/cd.dir/src/commands/cd.c.o
.PHONY : src/commands/cd.c.o

src/commands/cd.i: src/commands/cd.c.i

.PHONY : src/commands/cd.i

# target to preprocess a source file
src/commands/cd.c.i:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/cd.c.i
	$(MAKE) -f CMakeFiles/cd.dir/build.make CMakeFiles/cd.dir/src/commands/cd.c.i
.PHONY : src/commands/cd.c.i

src/commands/cd.s: src/commands/cd.c.s

.PHONY : src/commands/cd.s

# target to generate assembly for a file
src/commands/cd.c.s:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/cd.c.s
	$(MAKE) -f CMakeFiles/cd.dir/build.make CMakeFiles/cd.dir/src/commands/cd.c.s
.PHONY : src/commands/cd.c.s

src/commands/chgrp.o: src/commands/chgrp.c.o

.PHONY : src/commands/chgrp.o

# target to build an object file
src/commands/chgrp.c.o:
	$(MAKE) -f CMakeFiles/chgrp.dir/build.make CMakeFiles/chgrp.dir/src/commands/chgrp.c.o
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/chgrp.c.o
	$(MAKE) -f CMakeFiles/chgrp_lib.dir/build.make CMakeFiles/chgrp_lib.dir/src/commands/chgrp.c.o
.PHONY : src/commands/chgrp.c.o

src/commands/chgrp.i: src/commands/chgrp.c.i

.PHONY : src/commands/chgrp.i

# target to preprocess a source file
src/commands/chgrp.c.i:
	$(MAKE) -f CMakeFiles/chgrp.dir/build.make CMakeFiles/chgrp.dir/src/commands/chgrp.c.i
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/chgrp.c.i
	$(MAKE) -f CMakeFiles/chgrp_lib.dir/build.make CMakeFiles/chgrp_lib.dir/src/commands/chgrp.c.i
.PHONY : src/commands/chgrp.c.i

src/commands/chgrp.s: src/commands/chgrp.c.s

.PHONY : src/commands/chgrp.s

# target to generate assembly for a file
src/commands/chgrp.c.s:
	$(MAKE) -f CMakeFiles/chgrp.dir/build.make CMakeFiles/chgrp.dir/src/commands/chgrp.c.s
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/chgrp.c.s
	$(MAKE) -f CMakeFiles/chgrp_lib.dir/build.make CMakeFiles/chgrp_lib.dir/src/commands/chgrp.c.s
.PHONY : src/commands/chgrp.c.s

src/commands/chmod.o: src/commands/chmod.c.o

.PHONY : src/commands/chmod.o

# target to build an object file
src/commands/chmod.c.o:
	$(MAKE) -f CMakeFiles/chmod_lib.dir/build.make CMakeFiles/chmod_lib.dir/src/commands/chmod.c.o
	$(MAKE) -f CMakeFiles/chmod.dir/build.make CMakeFiles/chmod.dir/src/commands/chmod.c.o
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/chmod.c.o
.PHONY : src/commands/chmod.c.o

src/commands/chmod.i: src/commands/chmod.c.i

.PHONY : src/commands/chmod.i

# target to preprocess a source file
src/commands/chmod.c.i:
	$(MAKE) -f CMakeFiles/chmod_lib.dir/build.make CMakeFiles/chmod_lib.dir/src/commands/chmod.c.i
	$(MAKE) -f CMakeFiles/chmod.dir/build.make CMakeFiles/chmod.dir/src/commands/chmod.c.i
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/chmod.c.i
.PHONY : src/commands/chmod.c.i

src/commands/chmod.s: src/commands/chmod.c.s

.PHONY : src/commands/chmod.s

# target to generate assembly for a file
src/commands/chmod.c.s:
	$(MAKE) -f CMakeFiles/chmod_lib.dir/build.make CMakeFiles/chmod_lib.dir/src/commands/chmod.c.s
	$(MAKE) -f CMakeFiles/chmod.dir/build.make CMakeFiles/chmod.dir/src/commands/chmod.c.s
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/chmod.c.s
.PHONY : src/commands/chmod.c.s

src/commands/chown.o: src/commands/chown.c.o

.PHONY : src/commands/chown.o

# target to build an object file
src/commands/chown.c.o:
	$(MAKE) -f CMakeFiles/chown_lib.dir/build.make CMakeFiles/chown_lib.dir/src/commands/chown.c.o
	$(MAKE) -f CMakeFiles/chown.dir/build.make CMakeFiles/chown.dir/src/commands/chown.c.o
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/chown.c.o
.PHONY : src/commands/chown.c.o

src/commands/chown.i: src/commands/chown.c.i

.PHONY : src/commands/chown.i

# target to preprocess a source file
src/commands/chown.c.i:
	$(MAKE) -f CMakeFiles/chown_lib.dir/build.make CMakeFiles/chown_lib.dir/src/commands/chown.c.i
	$(MAKE) -f CMakeFiles/chown.dir/build.make CMakeFiles/chown.dir/src/commands/chown.c.i
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/chown.c.i
.PHONY : src/commands/chown.c.i

src/commands/chown.s: src/commands/chown.c.s

.PHONY : src/commands/chown.s

# target to generate assembly for a file
src/commands/chown.c.s:
	$(MAKE) -f CMakeFiles/chown_lib.dir/build.make CMakeFiles/chown_lib.dir/src/commands/chown.c.s
	$(MAKE) -f CMakeFiles/chown.dir/build.make CMakeFiles/chown.dir/src/commands/chown.c.s
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/chown.c.s
.PHONY : src/commands/chown.c.s

src/commands/clear.o: src/commands/clear.c.o

.PHONY : src/commands/clear.o

# target to build an object file
src/commands/clear.c.o:
	$(MAKE) -f CMakeFiles/clear_lib.dir/build.make CMakeFiles/clear_lib.dir/src/commands/clear.c.o
	$(MAKE) -f CMakeFiles/clear.dir/build.make CMakeFiles/clear.dir/src/commands/clear.c.o
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/clear.c.o
.PHONY : src/commands/clear.c.o

src/commands/clear.i: src/commands/clear.c.i

.PHONY : src/commands/clear.i

# target to preprocess a source file
src/commands/clear.c.i:
	$(MAKE) -f CMakeFiles/clear_lib.dir/build.make CMakeFiles/clear_lib.dir/src/commands/clear.c.i
	$(MAKE) -f CMakeFiles/clear.dir/build.make CMakeFiles/clear.dir/src/commands/clear.c.i
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/clear.c.i
.PHONY : src/commands/clear.c.i

src/commands/clear.s: src/commands/clear.c.s

.PHONY : src/commands/clear.s

# target to generate assembly for a file
src/commands/clear.c.s:
	$(MAKE) -f CMakeFiles/clear_lib.dir/build.make CMakeFiles/clear_lib.dir/src/commands/clear.c.s
	$(MAKE) -f CMakeFiles/clear.dir/build.make CMakeFiles/clear.dir/src/commands/clear.c.s
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/clear.c.s
.PHONY : src/commands/clear.c.s

src/commands/connect.o: src/commands/connect.c.o

.PHONY : src/commands/connect.o

# target to build an object file
src/commands/connect.c.o:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/connect.c.o
	$(MAKE) -f CMakeFiles/connect.dir/build.make CMakeFiles/connect.dir/src/commands/connect.c.o
	$(MAKE) -f CMakeFiles/connect_lib.dir/build.make CMakeFiles/connect_lib.dir/src/commands/connect.c.o
.PHONY : src/commands/connect.c.o

src/commands/connect.i: src/commands/connect.c.i

.PHONY : src/commands/connect.i

# target to preprocess a source file
src/commands/connect.c.i:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/connect.c.i
	$(MAKE) -f CMakeFiles/connect.dir/build.make CMakeFiles/connect.dir/src/commands/connect.c.i
	$(MAKE) -f CMakeFiles/connect_lib.dir/build.make CMakeFiles/connect_lib.dir/src/commands/connect.c.i
.PHONY : src/commands/connect.c.i

src/commands/connect.s: src/commands/connect.c.s

.PHONY : src/commands/connect.s

# target to generate assembly for a file
src/commands/connect.c.s:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/connect.c.s
	$(MAKE) -f CMakeFiles/connect.dir/build.make CMakeFiles/connect.dir/src/commands/connect.c.s
	$(MAKE) -f CMakeFiles/connect_lib.dir/build.make CMakeFiles/connect_lib.dir/src/commands/connect.c.s
.PHONY : src/commands/connect.c.s

src/commands/cp.o: src/commands/cp.c.o

.PHONY : src/commands/cp.o

# target to build an object file
src/commands/cp.c.o:
	$(MAKE) -f CMakeFiles/cp.dir/build.make CMakeFiles/cp.dir/src/commands/cp.c.o
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/cp.c.o
	$(MAKE) -f CMakeFiles/cp_lib.dir/build.make CMakeFiles/cp_lib.dir/src/commands/cp.c.o
.PHONY : src/commands/cp.c.o

src/commands/cp.i: src/commands/cp.c.i

.PHONY : src/commands/cp.i

# target to preprocess a source file
src/commands/cp.c.i:
	$(MAKE) -f CMakeFiles/cp.dir/build.make CMakeFiles/cp.dir/src/commands/cp.c.i
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/cp.c.i
	$(MAKE) -f CMakeFiles/cp_lib.dir/build.make CMakeFiles/cp_lib.dir/src/commands/cp.c.i
.PHONY : src/commands/cp.c.i

src/commands/cp.s: src/commands/cp.c.s

.PHONY : src/commands/cp.s

# target to generate assembly for a file
src/commands/cp.c.s:
	$(MAKE) -f CMakeFiles/cp.dir/build.make CMakeFiles/cp.dir/src/commands/cp.c.s
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/cp.c.s
	$(MAKE) -f CMakeFiles/cp_lib.dir/build.make CMakeFiles/cp_lib.dir/src/commands/cp.c.s
.PHONY : src/commands/cp.c.s

src/commands/du.o: src/commands/du.c.o

.PHONY : src/commands/du.o

# target to build an object file
src/commands/du.c.o:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/du.c.o
	$(MAKE) -f CMakeFiles/du_lib.dir/build.make CMakeFiles/du_lib.dir/src/commands/du.c.o
	$(MAKE) -f CMakeFiles/du.dir/build.make CMakeFiles/du.dir/src/commands/du.c.o
.PHONY : src/commands/du.c.o

src/commands/du.i: src/commands/du.c.i

.PHONY : src/commands/du.i

# target to preprocess a source file
src/commands/du.c.i:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/du.c.i
	$(MAKE) -f CMakeFiles/du_lib.dir/build.make CMakeFiles/du_lib.dir/src/commands/du.c.i
	$(MAKE) -f CMakeFiles/du.dir/build.make CMakeFiles/du.dir/src/commands/du.c.i
.PHONY : src/commands/du.c.i

src/commands/du.s: src/commands/du.c.s

.PHONY : src/commands/du.s

# target to generate assembly for a file
src/commands/du.c.s:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/du.c.s
	$(MAKE) -f CMakeFiles/du_lib.dir/build.make CMakeFiles/du_lib.dir/src/commands/du.c.s
	$(MAKE) -f CMakeFiles/du.dir/build.make CMakeFiles/du.dir/src/commands/du.c.s
.PHONY : src/commands/du.c.s

src/commands/echo.o: src/commands/echo.c.o

.PHONY : src/commands/echo.o

# target to build an object file
src/commands/echo.c.o:
	$(MAKE) -f CMakeFiles/echo_lib.dir/build.make CMakeFiles/echo_lib.dir/src/commands/echo.c.o
	$(MAKE) -f CMakeFiles/echo.dir/build.make CMakeFiles/echo.dir/src/commands/echo.c.o
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/echo.c.o
.PHONY : src/commands/echo.c.o

src/commands/echo.i: src/commands/echo.c.i

.PHONY : src/commands/echo.i

# target to preprocess a source file
src/commands/echo.c.i:
	$(MAKE) -f CMakeFiles/echo_lib.dir/build.make CMakeFiles/echo_lib.dir/src/commands/echo.c.i
	$(MAKE) -f CMakeFiles/echo.dir/build.make CMakeFiles/echo.dir/src/commands/echo.c.i
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/echo.c.i
.PHONY : src/commands/echo.c.i

src/commands/echo.s: src/commands/echo.c.s

.PHONY : src/commands/echo.s

# target to generate assembly for a file
src/commands/echo.c.s:
	$(MAKE) -f CMakeFiles/echo_lib.dir/build.make CMakeFiles/echo_lib.dir/src/commands/echo.c.s
	$(MAKE) -f CMakeFiles/echo.dir/build.make CMakeFiles/echo.dir/src/commands/echo.c.s
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/echo.c.s
.PHONY : src/commands/echo.c.s

src/commands/ls.o: src/commands/ls.c.o

.PHONY : src/commands/ls.o

# target to build an object file
src/commands/ls.c.o:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/ls.c.o
	$(MAKE) -f CMakeFiles/ls.dir/build.make CMakeFiles/ls.dir/src/commands/ls.c.o
	$(MAKE) -f CMakeFiles/ls_lib.dir/build.make CMakeFiles/ls_lib.dir/src/commands/ls.c.o
.PHONY : src/commands/ls.c.o

src/commands/ls.i: src/commands/ls.c.i

.PHONY : src/commands/ls.i

# target to preprocess a source file
src/commands/ls.c.i:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/ls.c.i
	$(MAKE) -f CMakeFiles/ls.dir/build.make CMakeFiles/ls.dir/src/commands/ls.c.i
	$(MAKE) -f CMakeFiles/ls_lib.dir/build.make CMakeFiles/ls_lib.dir/src/commands/ls.c.i
.PHONY : src/commands/ls.c.i

src/commands/ls.s: src/commands/ls.c.s

.PHONY : src/commands/ls.s

# target to generate assembly for a file
src/commands/ls.c.s:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/ls.c.s
	$(MAKE) -f CMakeFiles/ls.dir/build.make CMakeFiles/ls.dir/src/commands/ls.c.s
	$(MAKE) -f CMakeFiles/ls_lib.dir/build.make CMakeFiles/ls_lib.dir/src/commands/ls.c.s
.PHONY : src/commands/ls.c.s

src/commands/mkdir.o: src/commands/mkdir.c.o

.PHONY : src/commands/mkdir.o

# target to build an object file
src/commands/mkdir.c.o:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/mkdir.c.o
	$(MAKE) -f CMakeFiles/mkdir.dir/build.make CMakeFiles/mkdir.dir/src/commands/mkdir.c.o
	$(MAKE) -f CMakeFiles/mkdir_lib.dir/build.make CMakeFiles/mkdir_lib.dir/src/commands/mkdir.c.o
.PHONY : src/commands/mkdir.c.o

src/commands/mkdir.i: src/commands/mkdir.c.i

.PHONY : src/commands/mkdir.i

# target to preprocess a source file
src/commands/mkdir.c.i:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/mkdir.c.i
	$(MAKE) -f CMakeFiles/mkdir.dir/build.make CMakeFiles/mkdir.dir/src/commands/mkdir.c.i
	$(MAKE) -f CMakeFiles/mkdir_lib.dir/build.make CMakeFiles/mkdir_lib.dir/src/commands/mkdir.c.i
.PHONY : src/commands/mkdir.c.i

src/commands/mkdir.s: src/commands/mkdir.c.s

.PHONY : src/commands/mkdir.s

# target to generate assembly for a file
src/commands/mkdir.c.s:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/mkdir.c.s
	$(MAKE) -f CMakeFiles/mkdir.dir/build.make CMakeFiles/mkdir.dir/src/commands/mkdir.c.s
	$(MAKE) -f CMakeFiles/mkdir_lib.dir/build.make CMakeFiles/mkdir_lib.dir/src/commands/mkdir.c.s
.PHONY : src/commands/mkdir.c.s

src/commands/more.o: src/commands/more.c.o

.PHONY : src/commands/more.o

# target to build an object file
src/commands/more.c.o:
	$(MAKE) -f CMakeFiles/more.dir/build.make CMakeFiles/more.dir/src/commands/more.c.o
	$(MAKE) -f CMakeFiles/more_lib.dir/build.make CMakeFiles/more_lib.dir/src/commands/more.c.o
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/more.c.o
.PHONY : src/commands/more.c.o

src/commands/more.i: src/commands/more.c.i

.PHONY : src/commands/more.i

# target to preprocess a source file
src/commands/more.c.i:
	$(MAKE) -f CMakeFiles/more.dir/build.make CMakeFiles/more.dir/src/commands/more.c.i
	$(MAKE) -f CMakeFiles/more_lib.dir/build.make CMakeFiles/more_lib.dir/src/commands/more.c.i
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/more.c.i
.PHONY : src/commands/more.c.i

src/commands/more.s: src/commands/more.c.s

.PHONY : src/commands/more.s

# target to generate assembly for a file
src/commands/more.c.s:
	$(MAKE) -f CMakeFiles/more.dir/build.make CMakeFiles/more.dir/src/commands/more.c.s
	$(MAKE) -f CMakeFiles/more_lib.dir/build.make CMakeFiles/more_lib.dir/src/commands/more.c.s
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/more.c.s
.PHONY : src/commands/more.c.s

src/commands/mv.o: src/commands/mv.c.o

.PHONY : src/commands/mv.o

# target to build an object file
src/commands/mv.c.o:
	$(MAKE) -f CMakeFiles/mv_lib.dir/build.make CMakeFiles/mv_lib.dir/src/commands/mv.c.o
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/mv.c.o
	$(MAKE) -f CMakeFiles/mv.dir/build.make CMakeFiles/mv.dir/src/commands/mv.c.o
.PHONY : src/commands/mv.c.o

src/commands/mv.i: src/commands/mv.c.i

.PHONY : src/commands/mv.i

# target to preprocess a source file
src/commands/mv.c.i:
	$(MAKE) -f CMakeFiles/mv_lib.dir/build.make CMakeFiles/mv_lib.dir/src/commands/mv.c.i
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/mv.c.i
	$(MAKE) -f CMakeFiles/mv.dir/build.make CMakeFiles/mv.dir/src/commands/mv.c.i
.PHONY : src/commands/mv.c.i

src/commands/mv.s: src/commands/mv.c.s

.PHONY : src/commands/mv.s

# target to generate assembly for a file
src/commands/mv.c.s:
	$(MAKE) -f CMakeFiles/mv_lib.dir/build.make CMakeFiles/mv_lib.dir/src/commands/mv.c.s
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/mv.c.s
	$(MAKE) -f CMakeFiles/mv.dir/build.make CMakeFiles/mv.dir/src/commands/mv.c.s
.PHONY : src/commands/mv.c.s

src/commands/ps.o: src/commands/ps.c.o

.PHONY : src/commands/ps.o

# target to build an object file
src/commands/ps.c.o:
	$(MAKE) -f CMakeFiles/ps_lib.dir/build.make CMakeFiles/ps_lib.dir/src/commands/ps.c.o
	$(MAKE) -f CMakeFiles/ps.dir/build.make CMakeFiles/ps.dir/src/commands/ps.c.o
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/ps.c.o
.PHONY : src/commands/ps.c.o

src/commands/ps.i: src/commands/ps.c.i

.PHONY : src/commands/ps.i

# target to preprocess a source file
src/commands/ps.c.i:
	$(MAKE) -f CMakeFiles/ps_lib.dir/build.make CMakeFiles/ps_lib.dir/src/commands/ps.c.i
	$(MAKE) -f CMakeFiles/ps.dir/build.make CMakeFiles/ps.dir/src/commands/ps.c.i
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/ps.c.i
.PHONY : src/commands/ps.c.i

src/commands/ps.s: src/commands/ps.c.s

.PHONY : src/commands/ps.s

# target to generate assembly for a file
src/commands/ps.c.s:
	$(MAKE) -f CMakeFiles/ps_lib.dir/build.make CMakeFiles/ps_lib.dir/src/commands/ps.c.s
	$(MAKE) -f CMakeFiles/ps.dir/build.make CMakeFiles/ps.dir/src/commands/ps.c.s
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/ps.c.s
.PHONY : src/commands/ps.c.s

src/commands/pwd.o: src/commands/pwd.c.o

.PHONY : src/commands/pwd.o

# target to build an object file
src/commands/pwd.c.o:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/pwd.c.o
	$(MAKE) -f CMakeFiles/pwd.dir/build.make CMakeFiles/pwd.dir/src/commands/pwd.c.o
	$(MAKE) -f CMakeFiles/pwd_lib.dir/build.make CMakeFiles/pwd_lib.dir/src/commands/pwd.c.o
.PHONY : src/commands/pwd.c.o

src/commands/pwd.i: src/commands/pwd.c.i

.PHONY : src/commands/pwd.i

# target to preprocess a source file
src/commands/pwd.c.i:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/pwd.c.i
	$(MAKE) -f CMakeFiles/pwd.dir/build.make CMakeFiles/pwd.dir/src/commands/pwd.c.i
	$(MAKE) -f CMakeFiles/pwd_lib.dir/build.make CMakeFiles/pwd_lib.dir/src/commands/pwd.c.i
.PHONY : src/commands/pwd.c.i

src/commands/pwd.s: src/commands/pwd.c.s

.PHONY : src/commands/pwd.s

# target to generate assembly for a file
src/commands/pwd.c.s:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/pwd.c.s
	$(MAKE) -f CMakeFiles/pwd.dir/build.make CMakeFiles/pwd.dir/src/commands/pwd.c.s
	$(MAKE) -f CMakeFiles/pwd_lib.dir/build.make CMakeFiles/pwd_lib.dir/src/commands/pwd.c.s
.PHONY : src/commands/pwd.c.s

src/commands/rm.o: src/commands/rm.c.o

.PHONY : src/commands/rm.o

# target to build an object file
src/commands/rm.c.o:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/rm.c.o
	$(MAKE) -f CMakeFiles/rm.dir/build.make CMakeFiles/rm.dir/src/commands/rm.c.o
	$(MAKE) -f CMakeFiles/rm_lib.dir/build.make CMakeFiles/rm_lib.dir/src/commands/rm.c.o
.PHONY : src/commands/rm.c.o

src/commands/rm.i: src/commands/rm.c.i

.PHONY : src/commands/rm.i

# target to preprocess a source file
src/commands/rm.c.i:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/rm.c.i
	$(MAKE) -f CMakeFiles/rm.dir/build.make CMakeFiles/rm.dir/src/commands/rm.c.i
	$(MAKE) -f CMakeFiles/rm_lib.dir/build.make CMakeFiles/rm_lib.dir/src/commands/rm.c.i
.PHONY : src/commands/rm.c.i

src/commands/rm.s: src/commands/rm.c.s

.PHONY : src/commands/rm.s

# target to generate assembly for a file
src/commands/rm.c.s:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/rm.c.s
	$(MAKE) -f CMakeFiles/rm.dir/build.make CMakeFiles/rm.dir/src/commands/rm.c.s
	$(MAKE) -f CMakeFiles/rm_lib.dir/build.make CMakeFiles/rm_lib.dir/src/commands/rm.c.s
.PHONY : src/commands/rm.c.s

src/commands/top.o: src/commands/top.c.o

.PHONY : src/commands/top.o

# target to build an object file
src/commands/top.c.o:
	$(MAKE) -f CMakeFiles/top_lib.dir/build.make CMakeFiles/top_lib.dir/src/commands/top.c.o
	$(MAKE) -f CMakeFiles/top.dir/build.make CMakeFiles/top.dir/src/commands/top.c.o
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/top.c.o
.PHONY : src/commands/top.c.o

src/commands/top.i: src/commands/top.c.i

.PHONY : src/commands/top.i

# target to preprocess a source file
src/commands/top.c.i:
	$(MAKE) -f CMakeFiles/top_lib.dir/build.make CMakeFiles/top_lib.dir/src/commands/top.c.i
	$(MAKE) -f CMakeFiles/top.dir/build.make CMakeFiles/top.dir/src/commands/top.c.i
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/top.c.i
.PHONY : src/commands/top.c.i

src/commands/top.s: src/commands/top.c.s

.PHONY : src/commands/top.s

# target to generate assembly for a file
src/commands/top.c.s:
	$(MAKE) -f CMakeFiles/top_lib.dir/build.make CMakeFiles/top_lib.dir/src/commands/top.c.s
	$(MAKE) -f CMakeFiles/top.dir/build.make CMakeFiles/top.dir/src/commands/top.c.s
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/commands/top.c.s
.PHONY : src/commands/top.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/main.c.s
.PHONY : src/main.c.s

src/main/cat.o: src/main/cat.c.o

.PHONY : src/main/cat.o

# target to build an object file
src/main/cat.c.o:
	$(MAKE) -f CMakeFiles/cat_lib.dir/build.make CMakeFiles/cat_lib.dir/src/main/cat.c.o
	$(MAKE) -f CMakeFiles/cat.dir/build.make CMakeFiles/cat.dir/src/main/cat.c.o
.PHONY : src/main/cat.c.o

src/main/cat.i: src/main/cat.c.i

.PHONY : src/main/cat.i

# target to preprocess a source file
src/main/cat.c.i:
	$(MAKE) -f CMakeFiles/cat_lib.dir/build.make CMakeFiles/cat_lib.dir/src/main/cat.c.i
	$(MAKE) -f CMakeFiles/cat.dir/build.make CMakeFiles/cat.dir/src/main/cat.c.i
.PHONY : src/main/cat.c.i

src/main/cat.s: src/main/cat.c.s

.PHONY : src/main/cat.s

# target to generate assembly for a file
src/main/cat.c.s:
	$(MAKE) -f CMakeFiles/cat_lib.dir/build.make CMakeFiles/cat_lib.dir/src/main/cat.c.s
	$(MAKE) -f CMakeFiles/cat.dir/build.make CMakeFiles/cat.dir/src/main/cat.c.s
.PHONY : src/main/cat.c.s

src/main/cd.o: src/main/cd.c.o

.PHONY : src/main/cd.o

# target to build an object file
src/main/cd.c.o:
	$(MAKE) -f CMakeFiles/cd.dir/build.make CMakeFiles/cd.dir/src/main/cd.c.o
.PHONY : src/main/cd.c.o

src/main/cd.i: src/main/cd.c.i

.PHONY : src/main/cd.i

# target to preprocess a source file
src/main/cd.c.i:
	$(MAKE) -f CMakeFiles/cd.dir/build.make CMakeFiles/cd.dir/src/main/cd.c.i
.PHONY : src/main/cd.c.i

src/main/cd.s: src/main/cd.c.s

.PHONY : src/main/cd.s

# target to generate assembly for a file
src/main/cd.c.s:
	$(MAKE) -f CMakeFiles/cd.dir/build.make CMakeFiles/cd.dir/src/main/cd.c.s
.PHONY : src/main/cd.c.s

src/main/chgrp.o: src/main/chgrp.c.o

.PHONY : src/main/chgrp.o

# target to build an object file
src/main/chgrp.c.o:
	$(MAKE) -f CMakeFiles/chgrp.dir/build.make CMakeFiles/chgrp.dir/src/main/chgrp.c.o
	$(MAKE) -f CMakeFiles/chgrp_lib.dir/build.make CMakeFiles/chgrp_lib.dir/src/main/chgrp.c.o
.PHONY : src/main/chgrp.c.o

src/main/chgrp.i: src/main/chgrp.c.i

.PHONY : src/main/chgrp.i

# target to preprocess a source file
src/main/chgrp.c.i:
	$(MAKE) -f CMakeFiles/chgrp.dir/build.make CMakeFiles/chgrp.dir/src/main/chgrp.c.i
	$(MAKE) -f CMakeFiles/chgrp_lib.dir/build.make CMakeFiles/chgrp_lib.dir/src/main/chgrp.c.i
.PHONY : src/main/chgrp.c.i

src/main/chgrp.s: src/main/chgrp.c.s

.PHONY : src/main/chgrp.s

# target to generate assembly for a file
src/main/chgrp.c.s:
	$(MAKE) -f CMakeFiles/chgrp.dir/build.make CMakeFiles/chgrp.dir/src/main/chgrp.c.s
	$(MAKE) -f CMakeFiles/chgrp_lib.dir/build.make CMakeFiles/chgrp_lib.dir/src/main/chgrp.c.s
.PHONY : src/main/chgrp.c.s

src/main/chmod.o: src/main/chmod.c.o

.PHONY : src/main/chmod.o

# target to build an object file
src/main/chmod.c.o:
	$(MAKE) -f CMakeFiles/chmod_lib.dir/build.make CMakeFiles/chmod_lib.dir/src/main/chmod.c.o
	$(MAKE) -f CMakeFiles/chmod.dir/build.make CMakeFiles/chmod.dir/src/main/chmod.c.o
.PHONY : src/main/chmod.c.o

src/main/chmod.i: src/main/chmod.c.i

.PHONY : src/main/chmod.i

# target to preprocess a source file
src/main/chmod.c.i:
	$(MAKE) -f CMakeFiles/chmod_lib.dir/build.make CMakeFiles/chmod_lib.dir/src/main/chmod.c.i
	$(MAKE) -f CMakeFiles/chmod.dir/build.make CMakeFiles/chmod.dir/src/main/chmod.c.i
.PHONY : src/main/chmod.c.i

src/main/chmod.s: src/main/chmod.c.s

.PHONY : src/main/chmod.s

# target to generate assembly for a file
src/main/chmod.c.s:
	$(MAKE) -f CMakeFiles/chmod_lib.dir/build.make CMakeFiles/chmod_lib.dir/src/main/chmod.c.s
	$(MAKE) -f CMakeFiles/chmod.dir/build.make CMakeFiles/chmod.dir/src/main/chmod.c.s
.PHONY : src/main/chmod.c.s

src/main/chown.o: src/main/chown.c.o

.PHONY : src/main/chown.o

# target to build an object file
src/main/chown.c.o:
	$(MAKE) -f CMakeFiles/chown_lib.dir/build.make CMakeFiles/chown_lib.dir/src/main/chown.c.o
	$(MAKE) -f CMakeFiles/chown.dir/build.make CMakeFiles/chown.dir/src/main/chown.c.o
.PHONY : src/main/chown.c.o

src/main/chown.i: src/main/chown.c.i

.PHONY : src/main/chown.i

# target to preprocess a source file
src/main/chown.c.i:
	$(MAKE) -f CMakeFiles/chown_lib.dir/build.make CMakeFiles/chown_lib.dir/src/main/chown.c.i
	$(MAKE) -f CMakeFiles/chown.dir/build.make CMakeFiles/chown.dir/src/main/chown.c.i
.PHONY : src/main/chown.c.i

src/main/chown.s: src/main/chown.c.s

.PHONY : src/main/chown.s

# target to generate assembly for a file
src/main/chown.c.s:
	$(MAKE) -f CMakeFiles/chown_lib.dir/build.make CMakeFiles/chown_lib.dir/src/main/chown.c.s
	$(MAKE) -f CMakeFiles/chown.dir/build.make CMakeFiles/chown.dir/src/main/chown.c.s
.PHONY : src/main/chown.c.s

src/main/clear.o: src/main/clear.c.o

.PHONY : src/main/clear.o

# target to build an object file
src/main/clear.c.o:
	$(MAKE) -f CMakeFiles/clear_lib.dir/build.make CMakeFiles/clear_lib.dir/src/main/clear.c.o
	$(MAKE) -f CMakeFiles/clear.dir/build.make CMakeFiles/clear.dir/src/main/clear.c.o
.PHONY : src/main/clear.c.o

src/main/clear.i: src/main/clear.c.i

.PHONY : src/main/clear.i

# target to preprocess a source file
src/main/clear.c.i:
	$(MAKE) -f CMakeFiles/clear_lib.dir/build.make CMakeFiles/clear_lib.dir/src/main/clear.c.i
	$(MAKE) -f CMakeFiles/clear.dir/build.make CMakeFiles/clear.dir/src/main/clear.c.i
.PHONY : src/main/clear.c.i

src/main/clear.s: src/main/clear.c.s

.PHONY : src/main/clear.s

# target to generate assembly for a file
src/main/clear.c.s:
	$(MAKE) -f CMakeFiles/clear_lib.dir/build.make CMakeFiles/clear_lib.dir/src/main/clear.c.s
	$(MAKE) -f CMakeFiles/clear.dir/build.make CMakeFiles/clear.dir/src/main/clear.c.s
.PHONY : src/main/clear.c.s

src/main/connect.o: src/main/connect.c.o

.PHONY : src/main/connect.o

# target to build an object file
src/main/connect.c.o:
	$(MAKE) -f CMakeFiles/connect.dir/build.make CMakeFiles/connect.dir/src/main/connect.c.o
	$(MAKE) -f CMakeFiles/connect_lib.dir/build.make CMakeFiles/connect_lib.dir/src/main/connect.c.o
.PHONY : src/main/connect.c.o

src/main/connect.i: src/main/connect.c.i

.PHONY : src/main/connect.i

# target to preprocess a source file
src/main/connect.c.i:
	$(MAKE) -f CMakeFiles/connect.dir/build.make CMakeFiles/connect.dir/src/main/connect.c.i
	$(MAKE) -f CMakeFiles/connect_lib.dir/build.make CMakeFiles/connect_lib.dir/src/main/connect.c.i
.PHONY : src/main/connect.c.i

src/main/connect.s: src/main/connect.c.s

.PHONY : src/main/connect.s

# target to generate assembly for a file
src/main/connect.c.s:
	$(MAKE) -f CMakeFiles/connect.dir/build.make CMakeFiles/connect.dir/src/main/connect.c.s
	$(MAKE) -f CMakeFiles/connect_lib.dir/build.make CMakeFiles/connect_lib.dir/src/main/connect.c.s
.PHONY : src/main/connect.c.s

src/main/cp.o: src/main/cp.c.o

.PHONY : src/main/cp.o

# target to build an object file
src/main/cp.c.o:
	$(MAKE) -f CMakeFiles/cp.dir/build.make CMakeFiles/cp.dir/src/main/cp.c.o
	$(MAKE) -f CMakeFiles/cp_lib.dir/build.make CMakeFiles/cp_lib.dir/src/main/cp.c.o
.PHONY : src/main/cp.c.o

src/main/cp.i: src/main/cp.c.i

.PHONY : src/main/cp.i

# target to preprocess a source file
src/main/cp.c.i:
	$(MAKE) -f CMakeFiles/cp.dir/build.make CMakeFiles/cp.dir/src/main/cp.c.i
	$(MAKE) -f CMakeFiles/cp_lib.dir/build.make CMakeFiles/cp_lib.dir/src/main/cp.c.i
.PHONY : src/main/cp.c.i

src/main/cp.s: src/main/cp.c.s

.PHONY : src/main/cp.s

# target to generate assembly for a file
src/main/cp.c.s:
	$(MAKE) -f CMakeFiles/cp.dir/build.make CMakeFiles/cp.dir/src/main/cp.c.s
	$(MAKE) -f CMakeFiles/cp_lib.dir/build.make CMakeFiles/cp_lib.dir/src/main/cp.c.s
.PHONY : src/main/cp.c.s

src/main/du.o: src/main/du.c.o

.PHONY : src/main/du.o

# target to build an object file
src/main/du.c.o:
	$(MAKE) -f CMakeFiles/du_lib.dir/build.make CMakeFiles/du_lib.dir/src/main/du.c.o
	$(MAKE) -f CMakeFiles/du.dir/build.make CMakeFiles/du.dir/src/main/du.c.o
.PHONY : src/main/du.c.o

src/main/du.i: src/main/du.c.i

.PHONY : src/main/du.i

# target to preprocess a source file
src/main/du.c.i:
	$(MAKE) -f CMakeFiles/du_lib.dir/build.make CMakeFiles/du_lib.dir/src/main/du.c.i
	$(MAKE) -f CMakeFiles/du.dir/build.make CMakeFiles/du.dir/src/main/du.c.i
.PHONY : src/main/du.c.i

src/main/du.s: src/main/du.c.s

.PHONY : src/main/du.s

# target to generate assembly for a file
src/main/du.c.s:
	$(MAKE) -f CMakeFiles/du_lib.dir/build.make CMakeFiles/du_lib.dir/src/main/du.c.s
	$(MAKE) -f CMakeFiles/du.dir/build.make CMakeFiles/du.dir/src/main/du.c.s
.PHONY : src/main/du.c.s

src/main/echo.o: src/main/echo.c.o

.PHONY : src/main/echo.o

# target to build an object file
src/main/echo.c.o:
	$(MAKE) -f CMakeFiles/echo_lib.dir/build.make CMakeFiles/echo_lib.dir/src/main/echo.c.o
	$(MAKE) -f CMakeFiles/echo.dir/build.make CMakeFiles/echo.dir/src/main/echo.c.o
.PHONY : src/main/echo.c.o

src/main/echo.i: src/main/echo.c.i

.PHONY : src/main/echo.i

# target to preprocess a source file
src/main/echo.c.i:
	$(MAKE) -f CMakeFiles/echo_lib.dir/build.make CMakeFiles/echo_lib.dir/src/main/echo.c.i
	$(MAKE) -f CMakeFiles/echo.dir/build.make CMakeFiles/echo.dir/src/main/echo.c.i
.PHONY : src/main/echo.c.i

src/main/echo.s: src/main/echo.c.s

.PHONY : src/main/echo.s

# target to generate assembly for a file
src/main/echo.c.s:
	$(MAKE) -f CMakeFiles/echo_lib.dir/build.make CMakeFiles/echo_lib.dir/src/main/echo.c.s
	$(MAKE) -f CMakeFiles/echo.dir/build.make CMakeFiles/echo.dir/src/main/echo.c.s
.PHONY : src/main/echo.c.s

src/main/ls.o: src/main/ls.c.o

.PHONY : src/main/ls.o

# target to build an object file
src/main/ls.c.o:
	$(MAKE) -f CMakeFiles/ls.dir/build.make CMakeFiles/ls.dir/src/main/ls.c.o
	$(MAKE) -f CMakeFiles/ls_lib.dir/build.make CMakeFiles/ls_lib.dir/src/main/ls.c.o
.PHONY : src/main/ls.c.o

src/main/ls.i: src/main/ls.c.i

.PHONY : src/main/ls.i

# target to preprocess a source file
src/main/ls.c.i:
	$(MAKE) -f CMakeFiles/ls.dir/build.make CMakeFiles/ls.dir/src/main/ls.c.i
	$(MAKE) -f CMakeFiles/ls_lib.dir/build.make CMakeFiles/ls_lib.dir/src/main/ls.c.i
.PHONY : src/main/ls.c.i

src/main/ls.s: src/main/ls.c.s

.PHONY : src/main/ls.s

# target to generate assembly for a file
src/main/ls.c.s:
	$(MAKE) -f CMakeFiles/ls.dir/build.make CMakeFiles/ls.dir/src/main/ls.c.s
	$(MAKE) -f CMakeFiles/ls_lib.dir/build.make CMakeFiles/ls_lib.dir/src/main/ls.c.s
.PHONY : src/main/ls.c.s

src/main/mkdir.o: src/main/mkdir.c.o

.PHONY : src/main/mkdir.o

# target to build an object file
src/main/mkdir.c.o:
	$(MAKE) -f CMakeFiles/mkdir.dir/build.make CMakeFiles/mkdir.dir/src/main/mkdir.c.o
	$(MAKE) -f CMakeFiles/mkdir_lib.dir/build.make CMakeFiles/mkdir_lib.dir/src/main/mkdir.c.o
.PHONY : src/main/mkdir.c.o

src/main/mkdir.i: src/main/mkdir.c.i

.PHONY : src/main/mkdir.i

# target to preprocess a source file
src/main/mkdir.c.i:
	$(MAKE) -f CMakeFiles/mkdir.dir/build.make CMakeFiles/mkdir.dir/src/main/mkdir.c.i
	$(MAKE) -f CMakeFiles/mkdir_lib.dir/build.make CMakeFiles/mkdir_lib.dir/src/main/mkdir.c.i
.PHONY : src/main/mkdir.c.i

src/main/mkdir.s: src/main/mkdir.c.s

.PHONY : src/main/mkdir.s

# target to generate assembly for a file
src/main/mkdir.c.s:
	$(MAKE) -f CMakeFiles/mkdir.dir/build.make CMakeFiles/mkdir.dir/src/main/mkdir.c.s
	$(MAKE) -f CMakeFiles/mkdir_lib.dir/build.make CMakeFiles/mkdir_lib.dir/src/main/mkdir.c.s
.PHONY : src/main/mkdir.c.s

src/main/more.o: src/main/more.c.o

.PHONY : src/main/more.o

# target to build an object file
src/main/more.c.o:
	$(MAKE) -f CMakeFiles/more.dir/build.make CMakeFiles/more.dir/src/main/more.c.o
	$(MAKE) -f CMakeFiles/more_lib.dir/build.make CMakeFiles/more_lib.dir/src/main/more.c.o
.PHONY : src/main/more.c.o

src/main/more.i: src/main/more.c.i

.PHONY : src/main/more.i

# target to preprocess a source file
src/main/more.c.i:
	$(MAKE) -f CMakeFiles/more.dir/build.make CMakeFiles/more.dir/src/main/more.c.i
	$(MAKE) -f CMakeFiles/more_lib.dir/build.make CMakeFiles/more_lib.dir/src/main/more.c.i
.PHONY : src/main/more.c.i

src/main/more.s: src/main/more.c.s

.PHONY : src/main/more.s

# target to generate assembly for a file
src/main/more.c.s:
	$(MAKE) -f CMakeFiles/more.dir/build.make CMakeFiles/more.dir/src/main/more.c.s
	$(MAKE) -f CMakeFiles/more_lib.dir/build.make CMakeFiles/more_lib.dir/src/main/more.c.s
.PHONY : src/main/more.c.s

src/main/mv.o: src/main/mv.c.o

.PHONY : src/main/mv.o

# target to build an object file
src/main/mv.c.o:
	$(MAKE) -f CMakeFiles/mv_lib.dir/build.make CMakeFiles/mv_lib.dir/src/main/mv.c.o
	$(MAKE) -f CMakeFiles/mv.dir/build.make CMakeFiles/mv.dir/src/main/mv.c.o
.PHONY : src/main/mv.c.o

src/main/mv.i: src/main/mv.c.i

.PHONY : src/main/mv.i

# target to preprocess a source file
src/main/mv.c.i:
	$(MAKE) -f CMakeFiles/mv_lib.dir/build.make CMakeFiles/mv_lib.dir/src/main/mv.c.i
	$(MAKE) -f CMakeFiles/mv.dir/build.make CMakeFiles/mv.dir/src/main/mv.c.i
.PHONY : src/main/mv.c.i

src/main/mv.s: src/main/mv.c.s

.PHONY : src/main/mv.s

# target to generate assembly for a file
src/main/mv.c.s:
	$(MAKE) -f CMakeFiles/mv_lib.dir/build.make CMakeFiles/mv_lib.dir/src/main/mv.c.s
	$(MAKE) -f CMakeFiles/mv.dir/build.make CMakeFiles/mv.dir/src/main/mv.c.s
.PHONY : src/main/mv.c.s

src/main/ps.o: src/main/ps.c.o

.PHONY : src/main/ps.o

# target to build an object file
src/main/ps.c.o:
	$(MAKE) -f CMakeFiles/ps_lib.dir/build.make CMakeFiles/ps_lib.dir/src/main/ps.c.o
	$(MAKE) -f CMakeFiles/ps.dir/build.make CMakeFiles/ps.dir/src/main/ps.c.o
.PHONY : src/main/ps.c.o

src/main/ps.i: src/main/ps.c.i

.PHONY : src/main/ps.i

# target to preprocess a source file
src/main/ps.c.i:
	$(MAKE) -f CMakeFiles/ps_lib.dir/build.make CMakeFiles/ps_lib.dir/src/main/ps.c.i
	$(MAKE) -f CMakeFiles/ps.dir/build.make CMakeFiles/ps.dir/src/main/ps.c.i
.PHONY : src/main/ps.c.i

src/main/ps.s: src/main/ps.c.s

.PHONY : src/main/ps.s

# target to generate assembly for a file
src/main/ps.c.s:
	$(MAKE) -f CMakeFiles/ps_lib.dir/build.make CMakeFiles/ps_lib.dir/src/main/ps.c.s
	$(MAKE) -f CMakeFiles/ps.dir/build.make CMakeFiles/ps.dir/src/main/ps.c.s
.PHONY : src/main/ps.c.s

src/main/pwd.o: src/main/pwd.c.o

.PHONY : src/main/pwd.o

# target to build an object file
src/main/pwd.c.o:
	$(MAKE) -f CMakeFiles/pwd.dir/build.make CMakeFiles/pwd.dir/src/main/pwd.c.o
	$(MAKE) -f CMakeFiles/pwd_lib.dir/build.make CMakeFiles/pwd_lib.dir/src/main/pwd.c.o
.PHONY : src/main/pwd.c.o

src/main/pwd.i: src/main/pwd.c.i

.PHONY : src/main/pwd.i

# target to preprocess a source file
src/main/pwd.c.i:
	$(MAKE) -f CMakeFiles/pwd.dir/build.make CMakeFiles/pwd.dir/src/main/pwd.c.i
	$(MAKE) -f CMakeFiles/pwd_lib.dir/build.make CMakeFiles/pwd_lib.dir/src/main/pwd.c.i
.PHONY : src/main/pwd.c.i

src/main/pwd.s: src/main/pwd.c.s

.PHONY : src/main/pwd.s

# target to generate assembly for a file
src/main/pwd.c.s:
	$(MAKE) -f CMakeFiles/pwd.dir/build.make CMakeFiles/pwd.dir/src/main/pwd.c.s
	$(MAKE) -f CMakeFiles/pwd_lib.dir/build.make CMakeFiles/pwd_lib.dir/src/main/pwd.c.s
.PHONY : src/main/pwd.c.s

src/main/rm.o: src/main/rm.c.o

.PHONY : src/main/rm.o

# target to build an object file
src/main/rm.c.o:
	$(MAKE) -f CMakeFiles/rm.dir/build.make CMakeFiles/rm.dir/src/main/rm.c.o
	$(MAKE) -f CMakeFiles/rm_lib.dir/build.make CMakeFiles/rm_lib.dir/src/main/rm.c.o
.PHONY : src/main/rm.c.o

src/main/rm.i: src/main/rm.c.i

.PHONY : src/main/rm.i

# target to preprocess a source file
src/main/rm.c.i:
	$(MAKE) -f CMakeFiles/rm.dir/build.make CMakeFiles/rm.dir/src/main/rm.c.i
	$(MAKE) -f CMakeFiles/rm_lib.dir/build.make CMakeFiles/rm_lib.dir/src/main/rm.c.i
.PHONY : src/main/rm.c.i

src/main/rm.s: src/main/rm.c.s

.PHONY : src/main/rm.s

# target to generate assembly for a file
src/main/rm.c.s:
	$(MAKE) -f CMakeFiles/rm.dir/build.make CMakeFiles/rm.dir/src/main/rm.c.s
	$(MAKE) -f CMakeFiles/rm_lib.dir/build.make CMakeFiles/rm_lib.dir/src/main/rm.c.s
.PHONY : src/main/rm.c.s

src/main/top.o: src/main/top.c.o

.PHONY : src/main/top.o

# target to build an object file
src/main/top.c.o:
	$(MAKE) -f CMakeFiles/top_lib.dir/build.make CMakeFiles/top_lib.dir/src/main/top.c.o
	$(MAKE) -f CMakeFiles/top.dir/build.make CMakeFiles/top.dir/src/main/top.c.o
.PHONY : src/main/top.c.o

src/main/top.i: src/main/top.c.i

.PHONY : src/main/top.i

# target to preprocess a source file
src/main/top.c.i:
	$(MAKE) -f CMakeFiles/top_lib.dir/build.make CMakeFiles/top_lib.dir/src/main/top.c.i
	$(MAKE) -f CMakeFiles/top.dir/build.make CMakeFiles/top.dir/src/main/top.c.i
.PHONY : src/main/top.c.i

src/main/top.s: src/main/top.c.s

.PHONY : src/main/top.s

# target to generate assembly for a file
src/main/top.c.s:
	$(MAKE) -f CMakeFiles/top_lib.dir/build.make CMakeFiles/top_lib.dir/src/main/top.c.s
	$(MAKE) -f CMakeFiles/top.dir/build.make CMakeFiles/top.dir/src/main/top.c.s
.PHONY : src/main/top.c.s

src/process.o: src/process.c.o

.PHONY : src/process.o

# target to build an object file
src/process.c.o:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/process.c.o
.PHONY : src/process.c.o

src/process.i: src/process.c.i

.PHONY : src/process.i

# target to preprocess a source file
src/process.c.i:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/process.c.i
.PHONY : src/process.c.i

src/process.s: src/process.c.s

.PHONY : src/process.s

# target to generate assembly for a file
src/process.c.s:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/process.c.s
.PHONY : src/process.c.s

src/redirection.o: src/redirection.c.o

.PHONY : src/redirection.o

# target to build an object file
src/redirection.c.o:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/redirection.c.o
.PHONY : src/redirection.c.o

src/redirection.i: src/redirection.c.i

.PHONY : src/redirection.i

# target to preprocess a source file
src/redirection.c.i:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/redirection.c.i
.PHONY : src/redirection.c.i

src/redirection.s: src/redirection.c.s

.PHONY : src/redirection.s

# target to generate assembly for a file
src/redirection.c.s:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/redirection.c.s
.PHONY : src/redirection.c.s

src/server.o: src/server.c.o

.PHONY : src/server.o

# target to build an object file
src/server.c.o:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/server.c.o
.PHONY : src/server.c.o

src/server.i: src/server.c.i

.PHONY : src/server.i

# target to preprocess a source file
src/server.c.i:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/server.c.i
.PHONY : src/server.c.i

src/server.s: src/server.c.s

.PHONY : src/server.s

# target to generate assembly for a file
src/server.c.s:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/server.c.s
.PHONY : src/server.c.s

src/shell.o: src/shell.c.o

.PHONY : src/shell.o

# target to build an object file
src/shell.c.o:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/shell.c.o
.PHONY : src/shell.c.o

src/shell.i: src/shell.c.i

.PHONY : src/shell.i

# target to preprocess a source file
src/shell.c.i:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/shell.c.i
.PHONY : src/shell.c.i

src/shell.s: src/shell.c.s

.PHONY : src/shell.s

# target to generate assembly for a file
src/shell.c.s:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/shell.c.s
.PHONY : src/shell.c.s

src/utils.o: src/utils.c.o

.PHONY : src/utils.o

# target to build an object file
src/utils.c.o:
	$(MAKE) -f CMakeFiles/clear_lib.dir/build.make CMakeFiles/clear_lib.dir/src/utils.c.o
	$(MAKE) -f CMakeFiles/ps_lib.dir/build.make CMakeFiles/ps_lib.dir/src/utils.c.o
	$(MAKE) -f CMakeFiles/ps.dir/build.make CMakeFiles/ps.dir/src/utils.c.o
	$(MAKE) -f CMakeFiles/more.dir/build.make CMakeFiles/more.dir/src/utils.c.o
	$(MAKE) -f CMakeFiles/chgrp.dir/build.make CMakeFiles/chgrp.dir/src/utils.c.o
	$(MAKE) -f CMakeFiles/clear.dir/build.make CMakeFiles/clear.dir/src/utils.c.o
	$(MAKE) -f CMakeFiles/top_lib.dir/build.make CMakeFiles/top_lib.dir/src/utils.c.o
	$(MAKE) -f CMakeFiles/more_lib.dir/build.make CMakeFiles/more_lib.dir/src/utils.c.o
	$(MAKE) -f CMakeFiles/chown_lib.dir/build.make CMakeFiles/chown_lib.dir/src/utils.c.o
	$(MAKE) -f CMakeFiles/chown.dir/build.make CMakeFiles/chown.dir/src/utils.c.o
	$(MAKE) -f CMakeFiles/top.dir/build.make CMakeFiles/top.dir/src/utils.c.o
	$(MAKE) -f CMakeFiles/chmod_lib.dir/build.make CMakeFiles/chmod_lib.dir/src/utils.c.o
	$(MAKE) -f CMakeFiles/chmod.dir/build.make CMakeFiles/chmod.dir/src/utils.c.o
	$(MAKE) -f CMakeFiles/mv_lib.dir/build.make CMakeFiles/mv_lib.dir/src/utils.c.o
	$(MAKE) -f CMakeFiles/echo_lib.dir/build.make CMakeFiles/echo_lib.dir/src/utils.c.o
	$(MAKE) -f CMakeFiles/cp.dir/build.make CMakeFiles/cp.dir/src/utils.c.o
	$(MAKE) -f CMakeFiles/echo.dir/build.make CMakeFiles/echo.dir/src/utils.c.o
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/utils.c.o
	$(MAKE) -f CMakeFiles/du_lib.dir/build.make CMakeFiles/du_lib.dir/src/utils.c.o
	$(MAKE) -f CMakeFiles/cat_lib.dir/build.make CMakeFiles/cat_lib.dir/src/utils.c.o
	$(MAKE) -f CMakeFiles/ls.dir/build.make CMakeFiles/ls.dir/src/utils.c.o
	$(MAKE) -f CMakeFiles/ls_lib.dir/build.make CMakeFiles/ls_lib.dir/src/utils.c.o
	$(MAKE) -f CMakeFiles/pwd.dir/build.make CMakeFiles/pwd.dir/src/utils.c.o
	$(MAKE) -f CMakeFiles/chgrp_lib.dir/build.make CMakeFiles/chgrp_lib.dir/src/utils.c.o
	$(MAKE) -f CMakeFiles/cat.dir/build.make CMakeFiles/cat.dir/src/utils.c.o
	$(MAKE) -f CMakeFiles/pwd_lib.dir/build.make CMakeFiles/pwd_lib.dir/src/utils.c.o
	$(MAKE) -f CMakeFiles/rm.dir/build.make CMakeFiles/rm.dir/src/utils.c.o
	$(MAKE) -f CMakeFiles/mv.dir/build.make CMakeFiles/mv.dir/src/utils.c.o
	$(MAKE) -f CMakeFiles/mkdir.dir/build.make CMakeFiles/mkdir.dir/src/utils.c.o
	$(MAKE) -f CMakeFiles/mkdir_lib.dir/build.make CMakeFiles/mkdir_lib.dir/src/utils.c.o
	$(MAKE) -f CMakeFiles/rm_lib.dir/build.make CMakeFiles/rm_lib.dir/src/utils.c.o
	$(MAKE) -f CMakeFiles/du.dir/build.make CMakeFiles/du.dir/src/utils.c.o
	$(MAKE) -f CMakeFiles/connect.dir/build.make CMakeFiles/connect.dir/src/utils.c.o
	$(MAKE) -f CMakeFiles/connect_lib.dir/build.make CMakeFiles/connect_lib.dir/src/utils.c.o
	$(MAKE) -f CMakeFiles/cp_lib.dir/build.make CMakeFiles/cp_lib.dir/src/utils.c.o
.PHONY : src/utils.c.o

src/utils.i: src/utils.c.i

.PHONY : src/utils.i

# target to preprocess a source file
src/utils.c.i:
	$(MAKE) -f CMakeFiles/clear_lib.dir/build.make CMakeFiles/clear_lib.dir/src/utils.c.i
	$(MAKE) -f CMakeFiles/ps_lib.dir/build.make CMakeFiles/ps_lib.dir/src/utils.c.i
	$(MAKE) -f CMakeFiles/ps.dir/build.make CMakeFiles/ps.dir/src/utils.c.i
	$(MAKE) -f CMakeFiles/more.dir/build.make CMakeFiles/more.dir/src/utils.c.i
	$(MAKE) -f CMakeFiles/chgrp.dir/build.make CMakeFiles/chgrp.dir/src/utils.c.i
	$(MAKE) -f CMakeFiles/clear.dir/build.make CMakeFiles/clear.dir/src/utils.c.i
	$(MAKE) -f CMakeFiles/top_lib.dir/build.make CMakeFiles/top_lib.dir/src/utils.c.i
	$(MAKE) -f CMakeFiles/more_lib.dir/build.make CMakeFiles/more_lib.dir/src/utils.c.i
	$(MAKE) -f CMakeFiles/chown_lib.dir/build.make CMakeFiles/chown_lib.dir/src/utils.c.i
	$(MAKE) -f CMakeFiles/chown.dir/build.make CMakeFiles/chown.dir/src/utils.c.i
	$(MAKE) -f CMakeFiles/top.dir/build.make CMakeFiles/top.dir/src/utils.c.i
	$(MAKE) -f CMakeFiles/chmod_lib.dir/build.make CMakeFiles/chmod_lib.dir/src/utils.c.i
	$(MAKE) -f CMakeFiles/chmod.dir/build.make CMakeFiles/chmod.dir/src/utils.c.i
	$(MAKE) -f CMakeFiles/mv_lib.dir/build.make CMakeFiles/mv_lib.dir/src/utils.c.i
	$(MAKE) -f CMakeFiles/echo_lib.dir/build.make CMakeFiles/echo_lib.dir/src/utils.c.i
	$(MAKE) -f CMakeFiles/cp.dir/build.make CMakeFiles/cp.dir/src/utils.c.i
	$(MAKE) -f CMakeFiles/echo.dir/build.make CMakeFiles/echo.dir/src/utils.c.i
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/utils.c.i
	$(MAKE) -f CMakeFiles/du_lib.dir/build.make CMakeFiles/du_lib.dir/src/utils.c.i
	$(MAKE) -f CMakeFiles/cat_lib.dir/build.make CMakeFiles/cat_lib.dir/src/utils.c.i
	$(MAKE) -f CMakeFiles/ls.dir/build.make CMakeFiles/ls.dir/src/utils.c.i
	$(MAKE) -f CMakeFiles/ls_lib.dir/build.make CMakeFiles/ls_lib.dir/src/utils.c.i
	$(MAKE) -f CMakeFiles/pwd.dir/build.make CMakeFiles/pwd.dir/src/utils.c.i
	$(MAKE) -f CMakeFiles/chgrp_lib.dir/build.make CMakeFiles/chgrp_lib.dir/src/utils.c.i
	$(MAKE) -f CMakeFiles/cat.dir/build.make CMakeFiles/cat.dir/src/utils.c.i
	$(MAKE) -f CMakeFiles/pwd_lib.dir/build.make CMakeFiles/pwd_lib.dir/src/utils.c.i
	$(MAKE) -f CMakeFiles/rm.dir/build.make CMakeFiles/rm.dir/src/utils.c.i
	$(MAKE) -f CMakeFiles/mv.dir/build.make CMakeFiles/mv.dir/src/utils.c.i
	$(MAKE) -f CMakeFiles/mkdir.dir/build.make CMakeFiles/mkdir.dir/src/utils.c.i
	$(MAKE) -f CMakeFiles/mkdir_lib.dir/build.make CMakeFiles/mkdir_lib.dir/src/utils.c.i
	$(MAKE) -f CMakeFiles/rm_lib.dir/build.make CMakeFiles/rm_lib.dir/src/utils.c.i
	$(MAKE) -f CMakeFiles/du.dir/build.make CMakeFiles/du.dir/src/utils.c.i
	$(MAKE) -f CMakeFiles/connect.dir/build.make CMakeFiles/connect.dir/src/utils.c.i
	$(MAKE) -f CMakeFiles/connect_lib.dir/build.make CMakeFiles/connect_lib.dir/src/utils.c.i
	$(MAKE) -f CMakeFiles/cp_lib.dir/build.make CMakeFiles/cp_lib.dir/src/utils.c.i
.PHONY : src/utils.c.i

src/utils.s: src/utils.c.s

.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.c.s:
	$(MAKE) -f CMakeFiles/clear_lib.dir/build.make CMakeFiles/clear_lib.dir/src/utils.c.s
	$(MAKE) -f CMakeFiles/ps_lib.dir/build.make CMakeFiles/ps_lib.dir/src/utils.c.s
	$(MAKE) -f CMakeFiles/ps.dir/build.make CMakeFiles/ps.dir/src/utils.c.s
	$(MAKE) -f CMakeFiles/more.dir/build.make CMakeFiles/more.dir/src/utils.c.s
	$(MAKE) -f CMakeFiles/chgrp.dir/build.make CMakeFiles/chgrp.dir/src/utils.c.s
	$(MAKE) -f CMakeFiles/clear.dir/build.make CMakeFiles/clear.dir/src/utils.c.s
	$(MAKE) -f CMakeFiles/top_lib.dir/build.make CMakeFiles/top_lib.dir/src/utils.c.s
	$(MAKE) -f CMakeFiles/more_lib.dir/build.make CMakeFiles/more_lib.dir/src/utils.c.s
	$(MAKE) -f CMakeFiles/chown_lib.dir/build.make CMakeFiles/chown_lib.dir/src/utils.c.s
	$(MAKE) -f CMakeFiles/chown.dir/build.make CMakeFiles/chown.dir/src/utils.c.s
	$(MAKE) -f CMakeFiles/top.dir/build.make CMakeFiles/top.dir/src/utils.c.s
	$(MAKE) -f CMakeFiles/chmod_lib.dir/build.make CMakeFiles/chmod_lib.dir/src/utils.c.s
	$(MAKE) -f CMakeFiles/chmod.dir/build.make CMakeFiles/chmod.dir/src/utils.c.s
	$(MAKE) -f CMakeFiles/mv_lib.dir/build.make CMakeFiles/mv_lib.dir/src/utils.c.s
	$(MAKE) -f CMakeFiles/echo_lib.dir/build.make CMakeFiles/echo_lib.dir/src/utils.c.s
	$(MAKE) -f CMakeFiles/cp.dir/build.make CMakeFiles/cp.dir/src/utils.c.s
	$(MAKE) -f CMakeFiles/echo.dir/build.make CMakeFiles/echo.dir/src/utils.c.s
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/src/utils.c.s
	$(MAKE) -f CMakeFiles/du_lib.dir/build.make CMakeFiles/du_lib.dir/src/utils.c.s
	$(MAKE) -f CMakeFiles/cat_lib.dir/build.make CMakeFiles/cat_lib.dir/src/utils.c.s
	$(MAKE) -f CMakeFiles/ls.dir/build.make CMakeFiles/ls.dir/src/utils.c.s
	$(MAKE) -f CMakeFiles/ls_lib.dir/build.make CMakeFiles/ls_lib.dir/src/utils.c.s
	$(MAKE) -f CMakeFiles/pwd.dir/build.make CMakeFiles/pwd.dir/src/utils.c.s
	$(MAKE) -f CMakeFiles/chgrp_lib.dir/build.make CMakeFiles/chgrp_lib.dir/src/utils.c.s
	$(MAKE) -f CMakeFiles/cat.dir/build.make CMakeFiles/cat.dir/src/utils.c.s
	$(MAKE) -f CMakeFiles/pwd_lib.dir/build.make CMakeFiles/pwd_lib.dir/src/utils.c.s
	$(MAKE) -f CMakeFiles/rm.dir/build.make CMakeFiles/rm.dir/src/utils.c.s
	$(MAKE) -f CMakeFiles/mv.dir/build.make CMakeFiles/mv.dir/src/utils.c.s
	$(MAKE) -f CMakeFiles/mkdir.dir/build.make CMakeFiles/mkdir.dir/src/utils.c.s
	$(MAKE) -f CMakeFiles/mkdir_lib.dir/build.make CMakeFiles/mkdir_lib.dir/src/utils.c.s
	$(MAKE) -f CMakeFiles/rm_lib.dir/build.make CMakeFiles/rm_lib.dir/src/utils.c.s
	$(MAKE) -f CMakeFiles/du.dir/build.make CMakeFiles/du.dir/src/utils.c.s
	$(MAKE) -f CMakeFiles/connect.dir/build.make CMakeFiles/connect.dir/src/utils.c.s
	$(MAKE) -f CMakeFiles/connect_lib.dir/build.make CMakeFiles/connect_lib.dir/src/utils.c.s
	$(MAKE) -f CMakeFiles/cp_lib.dir/build.make CMakeFiles/cp_lib.dir/src/utils.c.s
.PHONY : src/utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... clear_lib"
	@echo "... ps_lib"
	@echo "... ps"
	@echo "... more"
	@echo "... chgrp"
	@echo "... clear"
	@echo "... top_lib"
	@echo "... more_lib"
	@echo "... chown_lib"
	@echo "... chown"
	@echo "... top"
	@echo "... chmod_lib"
	@echo "... edit_cache"
	@echo "... chmod"
	@echo "... mv_lib"
	@echo "... echo_lib"
	@echo "... cp"
	@echo "... echo"
	@echo "... shell"
	@echo "... du_lib"
	@echo "... cat_lib"
	@echo "... ls"
	@echo "... ls_lib"
	@echo "... pwd"
	@echo "... cd"
	@echo "... chgrp_lib"
	@echo "... cat"
	@echo "... pwd_lib"
	@echo "... rm"
	@echo "... mv"
	@echo "... mkdir"
	@echo "... mkdir_lib"
	@echo "... rm_lib"
	@echo "... du"
	@echo "... connect"
	@echo "... rebuild_cache"
	@echo "... connect_lib"
	@echo "... cp_lib"
	@echo "... src/commands.o"
	@echo "... src/commands.i"
	@echo "... src/commands.s"
	@echo "... src/commands/cat.o"
	@echo "... src/commands/cat.i"
	@echo "... src/commands/cat.s"
	@echo "... src/commands/cd.o"
	@echo "... src/commands/cd.i"
	@echo "... src/commands/cd.s"
	@echo "... src/commands/chgrp.o"
	@echo "... src/commands/chgrp.i"
	@echo "... src/commands/chgrp.s"
	@echo "... src/commands/chmod.o"
	@echo "... src/commands/chmod.i"
	@echo "... src/commands/chmod.s"
	@echo "... src/commands/chown.o"
	@echo "... src/commands/chown.i"
	@echo "... src/commands/chown.s"
	@echo "... src/commands/clear.o"
	@echo "... src/commands/clear.i"
	@echo "... src/commands/clear.s"
	@echo "... src/commands/connect.o"
	@echo "... src/commands/connect.i"
	@echo "... src/commands/connect.s"
	@echo "... src/commands/cp.o"
	@echo "... src/commands/cp.i"
	@echo "... src/commands/cp.s"
	@echo "... src/commands/du.o"
	@echo "... src/commands/du.i"
	@echo "... src/commands/du.s"
	@echo "... src/commands/echo.o"
	@echo "... src/commands/echo.i"
	@echo "... src/commands/echo.s"
	@echo "... src/commands/ls.o"
	@echo "... src/commands/ls.i"
	@echo "... src/commands/ls.s"
	@echo "... src/commands/mkdir.o"
	@echo "... src/commands/mkdir.i"
	@echo "... src/commands/mkdir.s"
	@echo "... src/commands/more.o"
	@echo "... src/commands/more.i"
	@echo "... src/commands/more.s"
	@echo "... src/commands/mv.o"
	@echo "... src/commands/mv.i"
	@echo "... src/commands/mv.s"
	@echo "... src/commands/ps.o"
	@echo "... src/commands/ps.i"
	@echo "... src/commands/ps.s"
	@echo "... src/commands/pwd.o"
	@echo "... src/commands/pwd.i"
	@echo "... src/commands/pwd.s"
	@echo "... src/commands/rm.o"
	@echo "... src/commands/rm.i"
	@echo "... src/commands/rm.s"
	@echo "... src/commands/top.o"
	@echo "... src/commands/top.i"
	@echo "... src/commands/top.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/main/cat.o"
	@echo "... src/main/cat.i"
	@echo "... src/main/cat.s"
	@echo "... src/main/cd.o"
	@echo "... src/main/cd.i"
	@echo "... src/main/cd.s"
	@echo "... src/main/chgrp.o"
	@echo "... src/main/chgrp.i"
	@echo "... src/main/chgrp.s"
	@echo "... src/main/chmod.o"
	@echo "... src/main/chmod.i"
	@echo "... src/main/chmod.s"
	@echo "... src/main/chown.o"
	@echo "... src/main/chown.i"
	@echo "... src/main/chown.s"
	@echo "... src/main/clear.o"
	@echo "... src/main/clear.i"
	@echo "... src/main/clear.s"
	@echo "... src/main/connect.o"
	@echo "... src/main/connect.i"
	@echo "... src/main/connect.s"
	@echo "... src/main/cp.o"
	@echo "... src/main/cp.i"
	@echo "... src/main/cp.s"
	@echo "... src/main/du.o"
	@echo "... src/main/du.i"
	@echo "... src/main/du.s"
	@echo "... src/main/echo.o"
	@echo "... src/main/echo.i"
	@echo "... src/main/echo.s"
	@echo "... src/main/ls.o"
	@echo "... src/main/ls.i"
	@echo "... src/main/ls.s"
	@echo "... src/main/mkdir.o"
	@echo "... src/main/mkdir.i"
	@echo "... src/main/mkdir.s"
	@echo "... src/main/more.o"
	@echo "... src/main/more.i"
	@echo "... src/main/more.s"
	@echo "... src/main/mv.o"
	@echo "... src/main/mv.i"
	@echo "... src/main/mv.s"
	@echo "... src/main/ps.o"
	@echo "... src/main/ps.i"
	@echo "... src/main/ps.s"
	@echo "... src/main/pwd.o"
	@echo "... src/main/pwd.i"
	@echo "... src/main/pwd.s"
	@echo "... src/main/rm.o"
	@echo "... src/main/rm.i"
	@echo "... src/main/rm.s"
	@echo "... src/main/top.o"
	@echo "... src/main/top.i"
	@echo "... src/main/top.s"
	@echo "... src/process.o"
	@echo "... src/process.i"
	@echo "... src/process.s"
	@echo "... src/redirection.o"
	@echo "... src/redirection.i"
	@echo "... src/redirection.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
	@echo "... src/shell.o"
	@echo "... src/shell.i"
	@echo "... src/shell.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

